#!/usr/bin/env bash
# test-glossary — `wip-plumbing glossary assemble|check` (step-13).
set -euo pipefail
cd "$(dirname "$0")/.."
_WIP_TEST_NAME="glossary"
# shellcheck source=test/helpers.sh
source test/helpers.sh

REPO_ROOT="$PWD"
SCRATCH="$(mktemp -d)"
trap 'rm -rf "$SCRATCH"' EXIT

# ---------------------------------------------------------------------------
# 1. Inclusion-rule data is the documented table (single source of truth).
# ---------------------------------------------------------------------------
rules="$(WIP_LIB="$REPO_ROOT/lib/wip" bash -c '
  source lib/wip/wip-plumbing-lib.bash
  source lib/wip/wip-plumbing-glossary-lib.bash
  wip_glossary_rules')"
expected_rules="core.md	always	true
orchestration.md	features.orchestration.enabled	.features.orchestration.enabled == true
solo.md	features.orchestration.backend	(.features.orchestration.enabled == true) and (.features.orchestration.backend == \"solo\")
lds.md	features.lds.enabled	.features.lds.enabled == true
diataxis.md	features.diataxis.enabled	.features.diataxis.enabled == true"
assert_eq "$expected_rules" "$rules" "wip_glossary_rules emits documented table"

# ---------------------------------------------------------------------------
# 2. Helper: build a tempdir manifest + templates dir, return paths.
# ---------------------------------------------------------------------------
make_tmp_repo() {
  local backend="$1" lds_enabled="${2:-false}" diataxis_enabled="${3:-false}" orch_enabled="${4:-true}"
  local tmp
  tmp="$(mktemp -d -p "$SCRATCH")"
  mkdir -p "$tmp/.wip" "$tmp/templates/glossary"
  cat >"$tmp/.wip.yaml" <<YAML
version: 1
gitignore:
  commit: false
  always_commit:
    - .wip/GLOSSARY.md
features:
  wip:
    enabled: true
  orchestration:
    enabled: $orch_enabled
    backend: $backend
  lds:
    enabled: $lds_enabled
  diataxis:
    enabled: $diataxis_enabled
  solo:
    enabled: true
current_initiative: test
initiatives:
  - slug: test
    title: Test
    status: in-flight
YAML
  cp "$REPO_ROOT"/templates/glossary/core.md "$tmp/templates/glossary/"
  cp "$REPO_ROOT"/templates/glossary/orchestration.md "$tmp/templates/glossary/"
  cp "$REPO_ROOT"/templates/glossary/solo.md "$tmp/templates/glossary/"
  printf '%s' "$tmp"
}

# ---------------------------------------------------------------------------
# 3. Assemble (this repo's actual manifest) — header + dividers + bodies.
# ---------------------------------------------------------------------------
out_file="$SCRATCH/repo-assemble.md"
bin/wip-plumbing glossary assemble >"$out_file"

assert_eq "# wip — Effective Glossary (this project)" "$(head -1 "$out_file")" "H1 line"
# shellcheck disable=SC2016
assert_grep '^<!-- GENERATED by `wip-plumbing glossary assemble`' "$out_file" "generated header line"
assert_grep 'Source:.*templates/glossary/{core,orchestration,solo}\.md' "$out_file" "Source path brace expansion"
assert_grep 'Driven by:.*features\.orchestration\.enabled.*features\.orchestration\.backend' "$out_file" "Driven-by lists active predicates"

# Per-partial dividers, in declaration order.
core_div=$(grep -n '^<!-- partial: core.md ' "$out_file" | head -1 | cut -d: -f1)
orch_div=$(grep -n '^<!-- partial: orchestration.md ' "$out_file" | head -1 | cut -d: -f1)
solo_div=$(grep -n '^<!-- partial: solo.md ' "$out_file" | head -1 | cut -d: -f1)
ordered="no"
if [[ -n "$core_div" && -n "$orch_div" && -n "$solo_div" &&
  "$core_div" -lt "$orch_div" && "$orch_div" -lt "$solo_div" ]]; then
  ordered="yes"
fi
assert_eq "yes" "$ordered" "per-partial dividers emit in declaration order"

# Strip rule: the partial-author HTML comment header MUST NOT appear in output.
assert_not_grep 'wip glossary partial: CORE' "$out_file" "partial CORE header stripped"
assert_not_grep 'wip glossary partial: ORCHESTRATION' "$out_file" "partial ORCHESTRATION header stripped"
assert_not_grep 'wip glossary partial: SOLO' "$out_file" "partial SOLO header stripped"

# Sentinel phrases — partial bodies are present.
assert_grep '^\*\*Layer rule:\*\*' "$out_file" "core sentinel present"
assert_grep '^## Roles' "$out_file" "orchestration sentinel present"
assert_grep '^## Solo backend (orchestration binding)' "$out_file" "solo sentinel present"

# ---------------------------------------------------------------------------
# 4. Predicate flips drop / include the right partial.
# ---------------------------------------------------------------------------
# (a) Base: orchestration + solo backend → all three.
tmp_a="$(make_tmp_repo solo false false true)"
out_a="$SCRATCH/a.md"
WIP_ROOT="$tmp_a" WIP_TEMPLATES_DIR="$tmp_a/templates" bin/wip-plumbing glossary assemble >"$out_a"
assert_grep '^## Solo backend' "$out_a" "tmp_a includes solo"

# (b) orchestration disabled → no orchestration, no solo.
tmp_b="$(make_tmp_repo solo false false false)"
out_b="$SCRATCH/b.md"
WIP_ROOT="$tmp_b" WIP_TEMPLATES_DIR="$tmp_b/templates" bin/wip-plumbing glossary assemble >"$out_b"
assert_not_grep '^## Roles' "$out_b" "tmp_b excludes orchestration"
assert_not_grep '^## Solo backend' "$out_b" "tmp_b excludes solo (orchestration off)"

# (c) orchestration enabled but backend != solo → orchestration kept, solo dropped.
tmp_c="$(make_tmp_repo native false false true)"
out_c="$SCRATCH/c.md"
WIP_ROOT="$tmp_c" WIP_TEMPLATES_DIR="$tmp_c/templates" bin/wip-plumbing glossary assemble >"$out_c"
assert_grep '^## Roles' "$out_c" "tmp_c includes orchestration"
assert_not_grep '^## Solo backend' "$out_c" "tmp_c excludes solo (backend != solo)"

# ---------------------------------------------------------------------------
# 5. Future-row graceful skip — diataxis enabled but partial not shipped.
# ---------------------------------------------------------------------------
tmp_d="$(make_tmp_repo solo false true true)"
rm -f "$tmp_d/templates/glossary/diataxis.md"
ledger_d="$(WIP_ROOT="$tmp_d" WIP_TEMPLATES_DIR="$tmp_d/templates" \
  bin/wip-plumbing glossary assemble --output .wip/GLOSSARY.md 2>/dev/null)"
assert_eq "true" "$(jq -r '.ok' <<<"$ledger_d")" "future-row assemble ok"
assert_eq "diataxis.md" "$(jq -r '.partials_skipped[0].name' <<<"$ledger_d")" "future-row skipped name"
assert_eq "predicate-true; partial-not-shipped" "$(jq -r '.partials_skipped[0].reason' <<<"$ledger_d")" "future-row skip reason"
assert_not_grep '^<!-- partial: diataxis\.md ' "$tmp_d/.wip/GLOSSARY.md" "future-row skip omits divider"

# ---------------------------------------------------------------------------
# 6. check — happy path against tempdir with fresh assemble on disk.
# ---------------------------------------------------------------------------
tmp_chk="$(make_tmp_repo solo false false true)"
WIP_ROOT="$tmp_chk" WIP_TEMPLATES_DIR="$tmp_chk/templates" bin/wip-plumbing glossary assemble \
  >"$tmp_chk/.wip/GLOSSARY.md"
set +e
out_chk="$(WIP_ROOT="$tmp_chk" WIP_TEMPLATES_DIR="$tmp_chk/templates" bin/wip-plumbing glossary check 2>/dev/null)"
rc_chk=$?
set -e
assert_eq "0" "$rc_chk" "check happy path exit 0"
assert_eq "true" "$(jq -r '.ok' <<<"$out_chk")" "check happy path ok:true"
assert_eq "false" "$(jq -r '.drift' <<<"$out_chk")" "check happy path drift:false"
assert_eq ".wip/GLOSSARY.md" "$(jq -r '.expected_path' <<<"$out_chk")" "check expected_path"

# ---------------------------------------------------------------------------
# 7. check — content drift.
# ---------------------------------------------------------------------------
printf '\nextra hand-edit\n' >>"$tmp_chk/.wip/GLOSSARY.md"
set +e
out_drift="$(WIP_ROOT="$tmp_chk" WIP_TEMPLATES_DIR="$tmp_chk/templates" bin/wip-plumbing glossary check 2>/dev/null)"
rc_drift=$?
set -e
assert_eq "4" "$rc_drift" "check content-drift exit 4"
assert_eq "true" "$(jq -r '.drift' <<<"$out_drift")" "check drift:true"
assert_eq "glossary-drift" "$(jq -r '.error.kind' <<<"$out_drift")" "check error.kind"
bd="$(jq -r '.byte_diff_count' <<<"$out_drift")"
[[ "$bd" -gt 0 ]] && bd_positive="yes" || bd_positive="no"
assert_eq "yes" "$bd_positive" "byte_diff_count > 0"

# ---------------------------------------------------------------------------
# 8. check — manifest drift (flip backend; on-disk is now stale).
# ---------------------------------------------------------------------------
tmp_mdr="$(make_tmp_repo solo false false true)"
WIP_ROOT="$tmp_mdr" WIP_TEMPLATES_DIR="$tmp_mdr/templates" bin/wip-plumbing glossary assemble \
  >"$tmp_mdr/.wip/GLOSSARY.md"
sed -i.bak 's/backend: solo/backend: native/' "$tmp_mdr/.wip.yaml" && rm -f "$tmp_mdr/.wip.yaml.bak"
set +e
out_mdr="$(WIP_ROOT="$tmp_mdr" WIP_TEMPLATES_DIR="$tmp_mdr/templates" bin/wip-plumbing glossary check 2>/dev/null)"
rc_mdr=$?
set -e
assert_eq "4" "$rc_mdr" "check manifest-drift exit 4"
assert_eq "true" "$(jq -r '.drift' <<<"$out_mdr")" "check manifest-drift drift:true"

# ---------------------------------------------------------------------------
# 9. --output writes the file (atomic mv) and emits a JSON ledger.
# ---------------------------------------------------------------------------
tmp_out="$(make_tmp_repo solo false false true)"
ledger="$(WIP_ROOT="$tmp_out" WIP_TEMPLATES_DIR="$tmp_out/templates" \
  bin/wip-plumbing glossary assemble --output .wip/GLOSSARY.md)"
assert_eq "true" "$(jq -r '.ok' <<<"$ledger")" "--output ledger ok"
assert_eq ".wip/GLOSSARY.md" "$(jq -r '.wrote[0]' <<<"$ledger")" "--output ledger wrote"
assert_file "$tmp_out/.wip/GLOSSARY.md" "--output file written"
# Source-inspection: assert the subcommand uses atomic mv (not cat >).
# shellcheck disable=SC2016
assert_grep 'mv -f "\$tmp" "\$abs_out"' \
  "$REPO_ROOT/lib/wip/wip-plumbing-subcommands/glossary.bash" \
  "--output uses atomic mv"

# --dry-run: emits ledger; file NOT created.
rm -f "$tmp_out/.wip/GLOSSARY.md"
ledger_dry="$(WIP_ROOT="$tmp_out" WIP_TEMPLATES_DIR="$tmp_out/templates" \
  bin/wip-plumbing --dry-run glossary assemble --output .wip/GLOSSARY.md)"
assert_eq "true" "$(jq -r '.dry_run' <<<"$ledger_dry")" "--dry-run flag in ledger"
assert_absent "$tmp_out/.wip/GLOSSARY.md" "--dry-run does not write"

# ---------------------------------------------------------------------------
# 10. Strip rule covers only the top block; later comments survive.
# ---------------------------------------------------------------------------
tmp_strip="$(make_tmp_repo solo false false true)"
cat >"$tmp_strip/templates/glossary/core.md" <<'STRIP_CORE'
<!-- wip glossary partial: CORE TEST. Should be stripped. -->

# Sample heading

A paragraph above the second comment.

<!-- This is a mid-document comment that MUST survive. -->

More content.
STRIP_CORE
out_strip="$SCRATCH/strip.md"
WIP_ROOT="$tmp_strip" WIP_TEMPLATES_DIR="$tmp_strip/templates" bin/wip-plumbing glossary assemble >"$out_strip"
assert_not_grep 'wip glossary partial: CORE TEST' "$out_strip" "strip rule removed top block"
assert_grep 'mid-document comment that MUST survive' "$out_strip" "strip rule preserved later comment"

# ---------------------------------------------------------------------------
# 11. WIP_TEMPLATES_DIR honored; bad-manifest / no-templates surface.
# ---------------------------------------------------------------------------
empty="$(mktemp -d -p "$SCRATCH")"
mkdir -p "$empty/.wip"
cat >"$empty/.wip.yaml" <<'YAML'
version: 1
features:
  wip:
    enabled: true
  orchestration:
    enabled: true
    backend: solo
YAML
set +e
out_nt="$(WIP_ROOT="$empty" WIP_TEMPLATES_DIR=/nonexistent/path bin/wip-plumbing glossary assemble 2>/dev/null)"
rc_nt=$?
set -e
assert_eq "4" "$rc_nt" "no-templates exit 4"
assert_eq "no-templates" "$(jq -r '.error.kind' <<<"$out_nt")" "no-templates error kind"

# ---------------------------------------------------------------------------
# 12. Bogus subcommand / no subcommand → exit 2.
# ---------------------------------------------------------------------------
set +e
bin/wip-plumbing glossary bogus >/dev/null 2>&1
rc_bs=$?
set -e
assert_eq "2" "$rc_bs" "bogus subcommand exit 2"
set +e
bin/wip-plumbing glossary >/dev/null 2>&1
rc_ns=$?
set -e
assert_eq "2" "$rc_ns" "no subcommand exit 2"

# ---------------------------------------------------------------------------
# 13. Pre-commit hook regression guard — committed tree's glossary is fresh.
# ---------------------------------------------------------------------------
set +e
out_repo="$(bin/wip-plumbing glossary check 2>/dev/null)"
rc_repo=$?
set -e
assert_eq "0" "$rc_repo" "repo's committed glossary exits 0 against check"
assert_eq "false" "$(jq -r '.drift' <<<"$out_repo")" "repo's committed glossary has no drift"

test_summary
