#!/usr/bin/env bash
# test-glossary — `wip-plumbing glossary assemble|check` (step-13).
set -euo pipefail
cd "$(dirname "$0")/.."
_WIP_TEST_NAME="glossary"
# shellcheck source=test/helpers.sh
source test/helpers.sh

REPO_ROOT="$PWD"
SCRATCH="$(mktemp -d)"
trap 'rm -rf "$SCRATCH"' EXIT

# ---------------------------------------------------------------------------
# 1. Inclusion-rule data is the documented table (single source of truth).
# ---------------------------------------------------------------------------
rules="$(WIP_LIB="$REPO_ROOT/lib/wip" bash -c '
  source lib/wip/wip-plumbing-lib.bash
  source lib/wip/wip-plumbing-glossary-lib.bash
  wip_glossary_rules')"
expected_rules="core.md	always	true
orchestration.md	features.orchestration.enabled	.features.orchestration.enabled == true
solo.md	features.orchestration.backend	(.features.orchestration.enabled == true) and (.features.orchestration.backend == \"solo\")
task.md	features.orchestration.backend	(.features.orchestration.enabled == true) and (.features.orchestration.backend == \"task\")
lds.md	features.lds.enabled	.features.lds.enabled == true
diataxis.md	features.diataxis.enabled	.features.diataxis.enabled == true"
assert_eq "$expected_rules" "$rules" "wip_glossary_rules emits documented table"

# ---------------------------------------------------------------------------
# 2. Helper: build a tempdir manifest + templates dir, return paths.
# ---------------------------------------------------------------------------
make_tmp_repo() {
  local backend="$1" lds_enabled="${2:-false}" diataxis_enabled="${3:-false}" orch_enabled="${4:-true}"
  local tmp
  tmp="$(mktemp -d -p "$SCRATCH")"
  mkdir -p "$tmp/.wip" "$tmp/templates/glossary"
  cat >"$tmp/.wip.yaml" <<YAML
version: 1
gitignore:
  commit: false
  always_commit:
    - .wip/GLOSSARY.md
features:
  wip:
    enabled: true
  orchestration:
    enabled: $orch_enabled
    backend: $backend
  lds:
    enabled: $lds_enabled
  diataxis:
    enabled: $diataxis_enabled
  solo:
    enabled: true
current_initiative: test
initiatives:
  - slug: test
    title: Test
    status: in-flight
YAML
  cp "$REPO_ROOT"/templates/glossary/core.md "$tmp/templates/glossary/"
  cp "$REPO_ROOT"/templates/glossary/orchestration.md "$tmp/templates/glossary/"
  cp "$REPO_ROOT"/templates/glossary/solo.md "$tmp/templates/glossary/"
  cp "$REPO_ROOT"/templates/glossary/task.md "$tmp/templates/glossary/"
  # Ship lds.md into the tmp templates dir only when lds is enabled, so the
  # positive-inclusion case (section 14) exercises it without disturbing the
  # diataxis graceful-skip case (section 5), which keeps its partial unshipped.
  if [[ "$lds_enabled" == "true" ]]; then
    cp "$REPO_ROOT"/templates/glossary/lds.md "$tmp/templates/glossary/"
  fi
  printf '%s' "$tmp"
}

# ---------------------------------------------------------------------------
# 3. Assemble (representative manifest fixture) — header + dividers + bodies.
#    Was the real repo manifest; that walks up for the gitignored .wip.yaml
#    (absent in CI → exit 4). A solo/orch fixture yields byte-identical output
#    for every assertion below, so all of §3 still runs in CI.
# ---------------------------------------------------------------------------
tmp_repo="$(make_tmp_repo solo false false true)"
out_file="$SCRATCH/repo-assemble.md"
WIP_ROOT="$tmp_repo" WIP_TEMPLATES_DIR="$tmp_repo/templates" \
  bin/wip-plumbing glossary assemble >"$out_file"

assert_eq "# wip — Effective Glossary (this project)" "$(head -1 "$out_file")" "H1 line"
# shellcheck disable=SC2016
assert_grep '^<!-- GENERATED by `wip-plumbing glossary assemble`' "$out_file" "generated header line"
assert_grep 'Source:.*templates/glossary/{core,orchestration,solo}\.md' "$out_file" "Source path brace expansion"
assert_grep 'Driven by:.*features\.orchestration\.enabled.*features\.orchestration\.backend' "$out_file" "Driven-by lists active predicates"

# Per-partial dividers, in declaration order.
core_div=$(grep -n '^<!-- partial: core.md ' "$out_file" | head -1 | cut -d: -f1)
orch_div=$(grep -n '^<!-- partial: orchestration.md ' "$out_file" | head -1 | cut -d: -f1)
solo_div=$(grep -n '^<!-- partial: solo.md ' "$out_file" | head -1 | cut -d: -f1)
ordered="no"
if [[ -n "$core_div" && -n "$orch_div" && -n "$solo_div" &&
  "$core_div" -lt "$orch_div" && "$orch_div" -lt "$solo_div" ]]; then
  ordered="yes"
fi
assert_eq "yes" "$ordered" "per-partial dividers emit in declaration order"

# Strip rule: the partial-author HTML comment header MUST NOT appear in output.
assert_not_grep 'wip glossary partial: CORE' "$out_file" "partial CORE header stripped"
assert_not_grep 'wip glossary partial: ORCHESTRATION' "$out_file" "partial ORCHESTRATION header stripped"
assert_not_grep 'wip glossary partial: SOLO' "$out_file" "partial SOLO header stripped"

# Sentinel phrases — partial bodies are present.
assert_grep '^\*\*Layer rule:\*\*' "$out_file" "core sentinel present"
assert_grep '^## Roles' "$out_file" "orchestration sentinel present"
assert_grep '^## Solo backend (orchestration binding)' "$out_file" "solo sentinel present"

# ---------------------------------------------------------------------------
# 4. Predicate flips drop / include the right partial.
# ---------------------------------------------------------------------------
# (a) Base: orchestration + solo backend → all three.
tmp_a="$(make_tmp_repo solo false false true)"
out_a="$SCRATCH/a.md"
WIP_ROOT="$tmp_a" WIP_TEMPLATES_DIR="$tmp_a/templates" bin/wip-plumbing glossary assemble >"$out_a"
assert_grep '^## Solo backend' "$out_a" "tmp_a includes solo"

# (b) orchestration disabled → no orchestration, no solo.
tmp_b="$(make_tmp_repo solo false false false)"
out_b="$SCRATCH/b.md"
WIP_ROOT="$tmp_b" WIP_TEMPLATES_DIR="$tmp_b/templates" bin/wip-plumbing glossary assemble >"$out_b"
assert_not_grep '^## Roles' "$out_b" "tmp_b excludes orchestration"
assert_not_grep '^## Solo backend' "$out_b" "tmp_b excludes solo (orchestration off)"

# (c) orchestration enabled but backend != solo/task → orchestration kept, both dropped.
tmp_c="$(make_tmp_repo native false false true)"
out_c="$SCRATCH/c.md"
WIP_ROOT="$tmp_c" WIP_TEMPLATES_DIR="$tmp_c/templates" bin/wip-plumbing glossary assemble >"$out_c"
assert_grep '^## Roles' "$out_c" "tmp_c includes orchestration"
assert_not_grep '^## Solo backend' "$out_c" "tmp_c excludes solo (backend != solo)"
assert_not_grep '^## Task backend' "$out_c" "tmp_c excludes task (backend != task)"

# (c2) backend: task → orchestration kept, task included, solo dropped (ADR-0013).
tmp_c2="$(make_tmp_repo task false false true)"
out_c2="$SCRATCH/c2.md"
WIP_ROOT="$tmp_c2" WIP_TEMPLATES_DIR="$tmp_c2/templates" bin/wip-plumbing glossary assemble >"$out_c2"
assert_grep '^## Roles' "$out_c2" "tmp_c2 includes orchestration"
assert_grep '^## Task backend (orchestration binding)' "$out_c2" "tmp_c2 includes task backend"
assert_not_grep '^## Solo backend' "$out_c2" "tmp_c2 excludes solo (backend == task)"

# ---------------------------------------------------------------------------
# 5. Future-row graceful skip — diataxis enabled but partial not shipped.
# ---------------------------------------------------------------------------
tmp_d="$(make_tmp_repo solo false true true)"
rm -f "$tmp_d/templates/glossary/diataxis.md"
ledger_d="$(WIP_ROOT="$tmp_d" WIP_TEMPLATES_DIR="$tmp_d/templates" \
  bin/wip-plumbing glossary assemble --output .wip/GLOSSARY.md 2>/dev/null)"
mapfile -t F < <(jq -r '.ok, .partials_skipped[0].name, .partials_skipped[0].reason' <<<"$ledger_d")
assert_eq "true" "${F[0]}" "future-row assemble ok"
assert_eq "diataxis.md" "${F[1]}" "future-row skipped name"
assert_eq "predicate-true; partial-not-shipped" "${F[2]}" "future-row skip reason"
assert_not_grep '^<!-- partial: diataxis\.md ' "$tmp_d/.wip/GLOSSARY.md" "future-row skip omits divider"

# ---------------------------------------------------------------------------
# 6. check — happy path against tempdir with fresh assemble on disk.
# ---------------------------------------------------------------------------
tmp_chk="$(make_tmp_repo solo false false true)"
WIP_ROOT="$tmp_chk" WIP_TEMPLATES_DIR="$tmp_chk/templates" bin/wip-plumbing glossary assemble \
  >"$tmp_chk/.wip/GLOSSARY.md"
set +e
out_chk="$(WIP_ROOT="$tmp_chk" WIP_TEMPLATES_DIR="$tmp_chk/templates" bin/wip-plumbing glossary check 2>/dev/null)"
rc_chk=$?
set -e
assert_eq "0" "$rc_chk" "check happy path exit 0"
mapfile -t F < <(jq -r '.ok, .drift, .expected_path' <<<"$out_chk")
assert_eq "true" "${F[0]}" "check happy path ok:true"
assert_eq "false" "${F[1]}" "check happy path drift:false"
assert_eq ".wip/GLOSSARY.md" "${F[2]}" "check expected_path"

# ---------------------------------------------------------------------------
# 7. check — content drift.
# ---------------------------------------------------------------------------
printf '\nextra hand-edit\n' >>"$tmp_chk/.wip/GLOSSARY.md"
set +e
out_drift="$(WIP_ROOT="$tmp_chk" WIP_TEMPLATES_DIR="$tmp_chk/templates" bin/wip-plumbing glossary check 2>/dev/null)"
rc_drift=$?
set -e
assert_eq "4" "$rc_drift" "check content-drift exit 4"
mapfile -t F < <(jq -r '.drift, .error.kind, .byte_diff_count' <<<"$out_drift")
assert_eq "true" "${F[0]}" "check drift:true"
assert_eq "glossary-drift" "${F[1]}" "check error.kind"
[[ "${F[2]}" -gt 0 ]] && bd_positive="yes" || bd_positive="no"
assert_eq "yes" "$bd_positive" "byte_diff_count > 0"

# ---------------------------------------------------------------------------
# 8. check — manifest drift (flip backend; on-disk is now stale).
# ---------------------------------------------------------------------------
tmp_mdr="$(make_tmp_repo solo false false true)"
WIP_ROOT="$tmp_mdr" WIP_TEMPLATES_DIR="$tmp_mdr/templates" bin/wip-plumbing glossary assemble \
  >"$tmp_mdr/.wip/GLOSSARY.md"
sed -i.bak 's/backend: solo/backend: native/' "$tmp_mdr/.wip.yaml" && rm -f "$tmp_mdr/.wip.yaml.bak"
set +e
out_mdr="$(WIP_ROOT="$tmp_mdr" WIP_TEMPLATES_DIR="$tmp_mdr/templates" bin/wip-plumbing glossary check 2>/dev/null)"
rc_mdr=$?
set -e
assert_eq "4" "$rc_mdr" "check manifest-drift exit 4"
assert_eq "true" "$(jq -r '.drift' <<<"$out_mdr")" "check manifest-drift drift:true"

# ---------------------------------------------------------------------------
# 9. --output writes the file (atomic mv) and emits a JSON ledger.
# ---------------------------------------------------------------------------
tmp_out="$(make_tmp_repo solo false false true)"
ledger="$(WIP_ROOT="$tmp_out" WIP_TEMPLATES_DIR="$tmp_out/templates" \
  bin/wip-plumbing glossary assemble --output .wip/GLOSSARY.md)"
mapfile -t F < <(jq -r '.ok, .wrote[0]' <<<"$ledger")
assert_eq "true" "${F[0]}" "--output ledger ok"
assert_eq ".wip/GLOSSARY.md" "${F[1]}" "--output ledger wrote"
assert_file "$tmp_out/.wip/GLOSSARY.md" "--output file written"
# Source-inspection: assert the subcommand uses atomic mv (not cat >).
# shellcheck disable=SC2016
assert_grep 'mv -f "\$tmp" "\$abs_out"' \
  "$REPO_ROOT/lib/wip/wip-plumbing-subcommands/glossary.bash" \
  "--output uses atomic mv"

# --dry-run: emits ledger; file NOT created.
rm -f "$tmp_out/.wip/GLOSSARY.md"
ledger_dry="$(WIP_ROOT="$tmp_out" WIP_TEMPLATES_DIR="$tmp_out/templates" \
  bin/wip-plumbing --dry-run glossary assemble --output .wip/GLOSSARY.md)"
assert_eq "true" "$(jq -r '.dry_run' <<<"$ledger_dry")" "--dry-run flag in ledger"
assert_absent "$tmp_out/.wip/GLOSSARY.md" "--dry-run does not write"

# ---------------------------------------------------------------------------
# 10. Strip rule covers only the top block; later comments survive.
# ---------------------------------------------------------------------------
tmp_strip="$(make_tmp_repo solo false false true)"
cat >"$tmp_strip/templates/glossary/core.md" <<'STRIP_CORE'
<!-- wip glossary partial: CORE TEST. Should be stripped. -->

# Sample heading

A paragraph above the second comment.

<!-- This is a mid-document comment that MUST survive. -->

More content.
STRIP_CORE
out_strip="$SCRATCH/strip.md"
WIP_ROOT="$tmp_strip" WIP_TEMPLATES_DIR="$tmp_strip/templates" bin/wip-plumbing glossary assemble >"$out_strip"
assert_not_grep 'wip glossary partial: CORE TEST' "$out_strip" "strip rule removed top block"
assert_grep 'mid-document comment that MUST survive' "$out_strip" "strip rule preserved later comment"

# ---------------------------------------------------------------------------
# 11. WIP_TEMPLATES_DIR honored; bad-manifest / no-templates surface.
# ---------------------------------------------------------------------------
empty="$(mktemp -d -p "$SCRATCH")"
mkdir -p "$empty/.wip"
cat >"$empty/.wip.yaml" <<'YAML'
version: 1
features:
  wip:
    enabled: true
  orchestration:
    enabled: true
    backend: solo
YAML
set +e
out_nt="$(WIP_ROOT="$empty" WIP_TEMPLATES_DIR=/nonexistent/path bin/wip-plumbing glossary assemble 2>/dev/null)"
rc_nt=$?
set -e
assert_eq "4" "$rc_nt" "no-templates exit 4"
assert_eq "no-templates" "$(jq -r '.error.kind' <<<"$out_nt")" "no-templates error kind"

# ---------------------------------------------------------------------------
# 12. Bogus subcommand / no subcommand → exit 2.
# ---------------------------------------------------------------------------
set +e
bin/wip-plumbing glossary bogus >/dev/null 2>&1
rc_bs=$?
set -e
assert_eq "2" "$rc_bs" "bogus subcommand exit 2"
set +e
bin/wip-plumbing glossary >/dev/null 2>&1
rc_ns=$?
set -e
assert_eq "2" "$rc_ns" "no subcommand exit 2"

# ---------------------------------------------------------------------------
# 13. Pre-commit hook regression guard — committed tree's glossary is fresh.
#     Reads the real (gitignored) .wip.yaml + .wip/GLOSSARY.md; both are absent
#     on a fresh CI checkout. This block's purpose IS validating the real
#     committed artifact, so it cannot be made hermetic — guard-skip in CI.
# ---------------------------------------------------------------------------
if [[ -f .wip.yaml && -f .wip/GLOSSARY.md ]]; then
  set +e
  out_repo="$(bin/wip-plumbing glossary check 2>/dev/null)"
  rc_repo=$?
  set -e
  assert_eq "0" "$rc_repo" "repo's committed glossary exits 0 against check"
  assert_eq "false" "$(jq -r '.drift' <<<"$out_repo")" "repo's committed glossary has no drift"
else
  printf '  skip (CI: gitignored .wip.yaml/.wip/GLOSSARY.md absent) — committed-glossary freshness guard\n'
fi

# ---------------------------------------------------------------------------
# 14. LDS partial — positive inclusion, ordering after solo, header strip.
# ---------------------------------------------------------------------------
tmp_lds="$(make_tmp_repo solo true false true)"
out_lds="$SCRATCH/lds.md"
WIP_ROOT="$tmp_lds" WIP_TEMPLATES_DIR="$tmp_lds/templates" bin/wip-plumbing glossary assemble >"$out_lds"

# Body sentinels — both lds sections are present.
assert_grep '^## Layered Documentation System' "$out_lds" "lds terms section present"
assert_grep '^## Graduation (LDS mechanism)' "$out_lds" "lds graduation section present"
# Divider emitted for the lds partial.
assert_grep '^<!-- partial: lds\.md ' "$out_lds" "lds divider emitted"
# Driven-by lists the lds predicate now that its body is on disk.
assert_grep 'Driven by:.*features\.lds\.enabled' "$out_lds" "Driven-by lists lds predicate"

# Ordering: lds divider must come after solo (declaration order core < orch < solo < lds).
solo_div_l=$(grep -n '^<!-- partial: solo.md ' "$out_lds" | head -1 | cut -d: -f1)
lds_div_l=$(grep -n '^<!-- partial: lds.md ' "$out_lds" | head -1 | cut -d: -f1)
lds_ordered="no"
if [[ -n "$solo_div_l" && -n "$lds_div_l" && "$solo_div_l" -lt "$lds_div_l" ]]; then
  lds_ordered="yes"
fi
assert_eq "yes" "$lds_ordered" "lds divider emits after solo"

# Strip rule: the lds partial-author comment header MUST NOT appear in output.
assert_not_grep 'wip glossary partial: LDS' "$out_lds" "partial LDS header stripped"

# check round-trips clean against the freshly-assembled lds glossary.
cp "$out_lds" "$tmp_lds/.wip/GLOSSARY.md"
set +e
out_lds_chk="$(WIP_ROOT="$tmp_lds" WIP_TEMPLATES_DIR="$tmp_lds/templates" bin/wip-plumbing glossary check 2>/dev/null)"
rc_lds_chk=$?
set -e
assert_eq "0" "$rc_lds_chk" "lds check exit 0"
mapfile -t F < <(jq -r '.ok, .drift' <<<"$out_lds_chk")
assert_eq "true" "${F[0]}" "lds check ok:true"
assert_eq "false" "${F[1]}" "lds check drift:false"

test_summary
