#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
_WIP_TEST_NAME="doctor-gitignore-tracked-but-undeclared"
# shellcheck source=test/helpers.sh
source test/helpers.sh

# §2n (kind:"gitignore-tracked", status:"gitignore-tracked-but-undeclared"): a path
# git TRACKS under `.wip/` that the manifest never declared in
# `gitignore.always_commit`. The mirror image of §2m, and the reason it exists at
# all: ignore rules never retroactively untrack an already-indexed file, so a file
# force-added under a blanket-ignored `.wip/` stays tracked forever with nothing
# pointing at it. The oracle is the INDEX (`git ls-files`), not the worktree —
# untracked files on disk are not drift, no matter how many of them there are.
#
# Real git repos per fixture (`git init` + `git add -f`), same as the §2m file.
# The healthy `.gitignore` is generated by the chunk-1 seam, not hand-written.
#
# HARD BOUNDARY (Orchestrator-signed-off): every fixture is a disposable tmp git
# repo. Nothing here touches the live repo's `.gitignore`, `.wip.yaml`, `.wip/`
# tree, or its index — in particular the live repo's own stray tracked workplan
# (the real-world instance of exactly this drift) is left alone for doctor to flag.
#
# Contract: workplan step-05 (.wip/initiatives/closeout-write-ladder/workplans/
# step-05-enforce-the-always-commit-gitignore-policy.md), Chunk 3.

export WIP_NO_REGISTRY=1

# shellcheck source=lib/wip/wip-plumbing-gitignore-lib.bash
source lib/wip/wip-plumbing-gitignore-lib.bash

# run_doctor <tmp> — run doctor under WIP_ROOT; set globals OUT (json) and RC.
run_doctor() {
  set +e
  OUT="$(WIP_ROOT="$1" bin/wip-plumbing doctor)"
  RC=$?
  set -e
}

n_declared() { jq '[.checks[] | select(.kind=="gitignore-declared")] | length' <<<"$OUT"; }
n_tracked() { jq "[.checks[] | select(.kind==\"gitignore-tracked\") | select(${1:-true})] | length" <<<"$OUT"; }

# mkrepo <tmp> — a real git repo with a wip fixture quiet for every other doctor
# check, `.gitignore` synced by the real generator, and the two declared files
# tracked in the index. `git add` (no commit) is enough: `ls-files` reads the index,
# so no committer identity is needed.
mkrepo() {
  local tmp="$1"
  wip_fixture_init "$tmp" --no-active-step
  cat >>"$tmp/.wip.yaml" <<'YAML'
gitignore:
  always_commit:
    - .wip/GLOSSARY.md
    - .wip/backlog.md
YAML
  cat >"$tmp/.wip/initiatives/demo/roadmap.md" <<'MD'
# Roadmap — demo

## Round 1 — One

- **step-01 — First** — current.
MD
  printf 'glossary\n' >"$tmp/.wip/GLOSSARY.md"
  printf 'backlog\n' >"$tmp/.wip/backlog.md"
  cat >"$tmp/.gitignore" <<'GI'
.direnv/
.DS_Store

.wip.yaml
.wip/
GI
  git -C "$tmp" init -q
  _wip_gitignore_sync_always_commit "$tmp/.wip.yaml" "$tmp/.gitignore" >/dev/null
  git -C "$tmp" add .gitignore .wip/GLOSSARY.md .wip/backlog.md
}

# ── Case A: healthy/quiet baseline ───────────────────────────────────────────
# `.gitignore` synced, and `git ls-files .wip/` returns EXACTLY the two declared
# files. Both directions silent. Same fixture the vacuous-always-true guard is
# demonstrated against (see the commit message).
tmpA="$(wip_mktemp)"
mkrepo "$tmpA"
assert_eq $'.wip/GLOSSARY.md\n.wip/backlog.md' "$(git -C "$tmpA" ls-files -- .wip/ | sort)" \
  "healthy: the index holds exactly the 2 declared files"
run_doctor "$tmpA"
assert_eq "0" "$RC" "healthy: exit 0"
assert_eq "0" "$(n_tracked)" "healthy: no gitignore-tracked-but-undeclared entry"
assert_eq "0" "$(n_declared)" "healthy: no gitignore-declared-but-ignored entry either"
assert_eq "0" "$(jq -r '.drift_count' <<<"$OUT")" "healthy: zero drift overall"
assert_eq "true" "$(jq -r '.ok' <<<"$OUT")" "healthy: ok:true"

# ── Case B: §2n-only drift, concrete count ───────────────────────────────────
# One EXTRA undeclared file under `.wip/` is force-added — `git add -f`, exactly how
# the live repo's stray workplan actually got tracked, and under the SAME registered
# initiative's directory (a made-up `initiatives/<slug>/` dir would trip doctor's
# unregistered-initiative check and pollute the drift count with unrelated noise).
# `.gitignore` is still correctly synced, so §2m has nothing to say: exactly 1 and
# exactly 0.
STRAY=".wip/initiatives/demo/workplans/step-01-oops.md"
mkdir -p "$tmpA/.wip/initiatives/demo/workplans"
printf 'stray\n' >"$tmpA/$STRAY"
git -C "$tmpA" add -f "$STRAY"
run_doctor "$tmpA"
assert_eq "4" "$RC" "§2n-only: exit 4"
assert_eq "1" "$(n_tracked)" "§2n-only: EXACTLY 1 tracked-but-undeclared entry"
assert_eq "0" "$(n_declared)" "§2n-only: EXACTLY 0 declared-but-ignored entries (.gitignore is fine)"
assert_eq "1" "$(jq -r '.drift_count' <<<"$OUT")" "§2n-only: the stray file is the ONLY drift"
assert_eq "1" "$(n_tracked ".path==\"$STRAY\"")" "§2n-only: the entry names the exact stray path"
assert_eq "gitignore-tracked-but-undeclared" \
  "$(jq -r '.checks[]|select(.kind=="gitignore-tracked").status' <<<"$OUT")" \
  "§2n-only: status is gitignore-tracked-but-undeclared"
assert_eq "either add $STRAY to gitignore.always_commit in .wip.yaml, or git rm --cached $STRAY if it was tracked in error" \
  "$(jq -r '.checks[]|select(.kind=="gitignore-tracked").fix' <<<"$OUT")" \
  "§2n-only: fix offers both resolutions, naming the path"

# ...and the declared files, which ARE tracked, are NOT flagged: being in the index
# is only drift when the manifest never declared you. (A §2n wired to flag every
# tracked path — or to flag declared-but-untracked ones — would blow this up.)
assert_eq "0" "$(n_tracked '.path==".wip/GLOSSARY.md"')" "§2n-only: declared+tracked GLOSSARY.md not flagged"
assert_eq "0" "$(n_tracked '.path==".wip/backlog.md"')" "§2n-only: declared+tracked backlog.md not flagged"

# ── Case C: untracked strays are not drift ───────────────────────────────────
# The same stray file, un-added (still on disk). §2n reads the index, so it must go
# quiet — a check that walked the worktree instead would still fire here.
git -C "$tmpA" rm --cached -q "$STRAY"
assert_file "$tmpA/$STRAY" "untracked stray: file is still on disk"
run_doctor "$tmpA"
assert_eq "0" "$RC" "untracked stray: exit 0"
assert_eq "0" "$(n_tracked)" "untracked stray: on-disk-but-unindexed is not drift"
assert_eq "0" "$(jq -r '.drift_count' <<<"$OUT")" "untracked stray: zero drift"

# ── Case D: a tracked declared file is not §2m drift — the index wins ────────
# The one place the two checks' oracles interact, pinned because it is genuinely
# surprising: `git check-ignore` reports a TRACKED path as not-ignored, whatever
# `.gitignore` says (an ignore rule never untracks an indexed file). So a declared
# file that is already tracked satisfies the policy — "these files stay tracked" —
# even with the generated block missing, and §2m stays quiet. It is the UNTRACKED
# declared file that §2m exists to catch, which is the state the live repo is in and
# the state the sibling test file's fixtures use throughout.
grep -v -e '^# --- wip: gitignore\.always_commit' -e '^# --- end wip: gitignore\.always_commit' \
  -e '^!\.wip/' -e '^\.wip/\*$' "$tmpA/.gitignore" >"$tmpA/.gitignore.tmp"
mv "$tmpA/.gitignore.tmp" "$tmpA/.gitignore"
run_doctor "$tmpA"
assert_eq "0" "$(n_declared)" "block deleted but files tracked: §2m quiet — the index already keeps the promise"
assert_eq "0" "$(jq -r '.drift_count' <<<"$OUT")" "block deleted but files tracked: zero drift"

# ...untrack them and the SAME `.gitignore` is now real drift: 2 entries. The
# difference between quiet and loud here is the index, nothing else.
git -C "$tmpA" rm --cached -q .wip/GLOSSARY.md .wip/backlog.md
run_doctor "$tmpA"
assert_eq "4" "$RC" "same .gitignore, now untracked: exit 4"
assert_eq "2" "$(n_declared)" "same .gitignore, now untracked: EXACTLY 2 §2m entries"
assert_eq "0" "$(n_tracked)" "same .gitignore, now untracked: still 0 §2n entries"

# ── Case E: both directions at once, each counted separately ─────────────────
# Two undeclared strays force-added, the declared files untracked, and the generated
# block deleted. Proves the two checks ADD UP rather than aliasing: 2 §2m + 2 §2n = 4
# distinct drift entries, no double-counting and no union/intersection collapse.
tmpE="$(wip_mktemp)"
mkrepo "$tmpE"
git -C "$tmpE" rm --cached -q .wip/GLOSSARY.md .wip/backlog.md
mkdir -p "$tmpE/.wip/initiatives/demo/workplans"
printf 'a\n' >"$tmpE/.wip/one.md"
printf 'b\n' >"$tmpE/.wip/initiatives/demo/workplans/two.md"
git -C "$tmpE" add -f .wip/one.md .wip/initiatives/demo/workplans/two.md
grep -v -e '^# --- wip: gitignore\.always_commit' -e '^# --- end wip: gitignore\.always_commit' \
  -e '^!\.wip/' -e '^\.wip/\*$' "$tmpE/.gitignore" >"$tmpE/.gitignore.tmp"
mv "$tmpE/.gitignore.tmp" "$tmpE/.gitignore"
run_doctor "$tmpE"
assert_eq "4" "$RC" "both directions: exit 4"
assert_eq "2" "$(n_declared)" "both directions: 2 declared-but-ignored"
assert_eq "2" "$(n_tracked)" "both directions: 2 tracked-but-undeclared"
assert_eq "4" "$(jq -r '.drift_count' <<<"$OUT")" "both directions: 4 drift entries, no double-counting"
assert_eq "1" "$(n_tracked '.path==".wip/one.md"')" "both directions: top-level stray named"
assert_eq "1" "$(n_tracked '.path==".wip/initiatives/demo/workplans/two.md"')" \
  "both directions: nested stray named"

# ── Case F: git-unavailable fallback ─────────────────────────────────────────
# Not a git worktree: ONE combined informational note, exit 0, no false positives.
# Neither direction is knowable without an index and an ignore resolver, and
# unknowable is not the same as broken.
tmpF="$(wip_mktemp)"
mkrepo "$tmpF"
rm -rf "$tmpF/.git"
run_doctor "$tmpF"
assert_eq "0" "$RC" "no git repo: exit 0"
assert_eq "1" "$(jq '[.checks[]|select(.kind=="gitignore")]|length' <<<"$OUT")" \
  "no git repo: ONE combined note for both checks"
assert_eq "ok" "$(jq -r '.checks[]|select(.kind=="gitignore").status' <<<"$OUT")" \
  "no git repo: informational status ok"
assert_eq "unavailable" "$(jq -r '.checks[]|select(.kind=="gitignore").probe' <<<"$OUT")" \
  "no git repo: probe unavailable"
assert_eq "0" "$(n_tracked)" "no git repo: no §2n entries"
assert_eq "0" "$(n_declared)" "no git repo: no §2m entries"
assert_eq "0" "$(jq -r '.drift_count' <<<"$OUT")" "no git repo: zero drift"

test_summary
